projects:
  boardtracker:
    schemaPath: amplify/backend/api/boardtracker/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/graphql.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
